global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'juneogo-node'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []